language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

addons:
  # If you don't use Chrome, or Firefox, remove the corresponding line
  chrome: stable
  firefox: latest

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 8.0

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - |
    if [[ $deps = low ]]; then
        export SYMFONY_DEPRECATIONS_HELPER=weak
        composer update --prefer-dist --prefer-lowest --prefer-stable
    else
        composer update --prefer-dist
    fi
  - ./vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS