language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

addons:
  # If you don't use Chrome, or Firefox, remove the corresponding line
  chrome: stable
  firefox: latest

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 8.0

before_install:
  - phpenv config-rm xdebug.ini || true
  - nvm use 16
  - npm i -g npm@8

install:
  - |
    if [[ $deps = low ]]; then
        export SYMFONY_DEPRECATIONS_HELPER=weak
        composer update --prefer-dist --prefer-lowest --prefer-stable
    else
        composer update --prefer-dist
    fi
  - npm install --global yarn
  - ./vendor/bin/simple-phpunit install

before_script:
  -  yarn --cwd ./src/Resources/assets install --force
  -  yarn --cwd ./tests/app install --force
  -  yarn --cwd ./src/Resources/assets yarn dev
  -  yarn --cwd ./tests/app install --force
  -  yarn --cwd ./tests/app dev
script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/bdi detect drivers
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS